//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursClient.ASP {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASP.ASPSoap")]
    public interface ASPSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Table", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Table(string Name_Table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Table", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_TableAsync(string Name_Table);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tovar_by_Cat_id", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Tovar_by_Cat_id(string category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Tovar_by_Cat_id", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Tovar_by_Cat_idAsync(string category_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Workers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Workers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Workers", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_WorkersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Rashod_1part", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Otchet_Rashod_1part(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Rashod_1part", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Rashod_1partAsync(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Rashod_2part", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Otchet_Rashod_2part(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Rashod_2part", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Rashod_2partAsync(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Prihod_1part", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Otchet_Prihod_1part(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Prihod_1part", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Prihod_1partAsync(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Prihod_2part", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet Get_Otchet_Prihod_2part(string TTN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Get_Otchet_Prihod_2part", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Prihod_2partAsync(string TTN);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ASPSoapChannel : KursClient.ASP.ASPSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ASPSoapClient : System.ServiceModel.ClientBase<KursClient.ASP.ASPSoap>, KursClient.ASP.ASPSoap {
        
        public ASPSoapClient() {
        }
        
        public ASPSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ASPSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ASPSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet Get_Table(string Name_Table) {
            return base.Channel.Get_Table(Name_Table);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_TableAsync(string Name_Table) {
            return base.Channel.Get_TableAsync(Name_Table);
        }
        
        public System.Data.DataSet Get_Tovar_by_Cat_id(string category_id) {
            return base.Channel.Get_Tovar_by_Cat_id(category_id);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Tovar_by_Cat_idAsync(string category_id) {
            return base.Channel.Get_Tovar_by_Cat_idAsync(category_id);
        }
        
        public System.Data.DataSet Get_Workers() {
            return base.Channel.Get_Workers();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_WorkersAsync() {
            return base.Channel.Get_WorkersAsync();
        }
        
        public System.Data.DataSet Get_Otchet_Rashod_1part(string TTN) {
            return base.Channel.Get_Otchet_Rashod_1part(TTN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Rashod_1partAsync(string TTN) {
            return base.Channel.Get_Otchet_Rashod_1partAsync(TTN);
        }
        
        public System.Data.DataSet Get_Otchet_Rashod_2part(string TTN) {
            return base.Channel.Get_Otchet_Rashod_2part(TTN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Rashod_2partAsync(string TTN) {
            return base.Channel.Get_Otchet_Rashod_2partAsync(TTN);
        }
        
        public System.Data.DataSet Get_Otchet_Prihod_1part(string TTN) {
            return base.Channel.Get_Otchet_Prihod_1part(TTN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Prihod_1partAsync(string TTN) {
            return base.Channel.Get_Otchet_Prihod_1partAsync(TTN);
        }
        
        public System.Data.DataSet Get_Otchet_Prihod_2part(string TTN) {
            return base.Channel.Get_Otchet_Prihod_2part(TTN);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> Get_Otchet_Prihod_2partAsync(string TTN) {
            return base.Channel.Get_Otchet_Prihod_2partAsync(TTN);
        }
    }
}
