//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KursClient.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.iWCF", CallbackContract=typeof(KursClient.WCF.iWCFCallback))]
    public interface iWCF {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/OnTimer")]
        void OnTimer(string Name_Table);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/OnTimer")]
        System.Threading.Tasks.Task OnTimerAsync(string Name_Table);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/NewClient")]
        void NewClient();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/NewClient")]
        System.Threading.Tasks.Task NewClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/CloseClient")]
        void CloseClient();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/CloseClient")]
        System.Threading.Tasks.Task CloseClientAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Delete_Line", ReplyAction="http://tempuri.org/iWCF/Delete_LineResponse")]
        string Delete_Line(string Name_Table, string key, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Delete_Line", ReplyAction="http://tempuri.org/iWCF/Delete_LineResponse")]
        System.Threading.Tasks.Task<string> Delete_LineAsync(string Name_Table, string key, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/Add_Line")]
        void Add_Line(string Name_Table, string value, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/Add_Line")]
        System.Threading.Tasks.Task Add_LineAsync(string Name_Table, string value, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/Ch_Line")]
        void Ch_Line(string Name_Table, string column, string value, string key, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/Ch_Line")]
        System.Threading.Tasks.Task Ch_LineAsync(string Name_Table, string column, string value, string key, string Primary);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Get_Tovar_dozakaz", ReplyAction="http://tempuri.org/iWCF/Get_Tovar_dozakazResponse")]
        string[][] Get_Tovar_dozakaz();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Get_Tovar_dozakaz", ReplyAction="http://tempuri.org/iWCF/Get_Tovar_dozakazResponse")]
        System.Threading.Tasks.Task<string[][]> Get_Tovar_dozakazAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Get_Tovar_izbytok", ReplyAction="http://tempuri.org/iWCF/Get_Tovar_izbytokResponse")]
        string[][] Get_Tovar_izbytok();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/Get_Tovar_izbytok", ReplyAction="http://tempuri.org/iWCF/Get_Tovar_izbytokResponse")]
        System.Threading.Tasks.Task<string[][]> Get_Tovar_izbytokAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/new_kol_after_prihod")]
        void new_kol_after_prihod(string nazva_tovara, string TTH, string kol);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/new_kol_after_prihod")]
        System.Threading.Tasks.Task new_kol_after_prihodAsync(string nazva_tovara, string TTH, string kol);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/new_kol_after_rashod")]
        void new_kol_after_rashod(string nazva_tovara, string TTH, string kol);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/new_kol_after_rashod")]
        System.Threading.Tasks.Task new_kol_after_rashodAsync(string nazva_tovara, string TTH, string kol);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/RecieveString", ReplyAction="http://tempuri.org/iWCF/RecieveStringResponse")]
        string RecieveString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/iWCF/RecieveString", ReplyAction="http://tempuri.org/iWCF/RecieveStringResponse")]
        System.Threading.Tasks.Task<string> RecieveStringAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iWCFCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/NewMessage")]
        void NewMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/iWCF/Update_client")]
        void Update_client(string NT, System.Data.DataSet ds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface iWCFChannel : KursClient.WCF.iWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class iWCFClient : System.ServiceModel.DuplexClientBase<KursClient.WCF.iWCF>, KursClient.WCF.iWCF {
        
        public iWCFClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public iWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public iWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public iWCFClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public iWCFClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void OnTimer(string Name_Table) {
            base.Channel.OnTimer(Name_Table);
        }
        
        public System.Threading.Tasks.Task OnTimerAsync(string Name_Table) {
            return base.Channel.OnTimerAsync(Name_Table);
        }
        
        public void NewClient() {
            base.Channel.NewClient();
        }
        
        public System.Threading.Tasks.Task NewClientAsync() {
            return base.Channel.NewClientAsync();
        }
        
        public void CloseClient() {
            base.Channel.CloseClient();
        }
        
        public System.Threading.Tasks.Task CloseClientAsync() {
            return base.Channel.CloseClientAsync();
        }
        
        public string Delete_Line(string Name_Table, string key, string Primary) {
            return base.Channel.Delete_Line(Name_Table, key, Primary);
        }
        
        public System.Threading.Tasks.Task<string> Delete_LineAsync(string Name_Table, string key, string Primary) {
            return base.Channel.Delete_LineAsync(Name_Table, key, Primary);
        }
        
        public void Add_Line(string Name_Table, string value, string Primary) {
            base.Channel.Add_Line(Name_Table, value, Primary);
        }
        
        public System.Threading.Tasks.Task Add_LineAsync(string Name_Table, string value, string Primary) {
            return base.Channel.Add_LineAsync(Name_Table, value, Primary);
        }
        
        public void Ch_Line(string Name_Table, string column, string value, string key, string Primary) {
            base.Channel.Ch_Line(Name_Table, column, value, key, Primary);
        }
        
        public System.Threading.Tasks.Task Ch_LineAsync(string Name_Table, string column, string value, string key, string Primary) {
            return base.Channel.Ch_LineAsync(Name_Table, column, value, key, Primary);
        }
        
        public string[][] Get_Tovar_dozakaz() {
            return base.Channel.Get_Tovar_dozakaz();
        }
        
        public System.Threading.Tasks.Task<string[][]> Get_Tovar_dozakazAsync() {
            return base.Channel.Get_Tovar_dozakazAsync();
        }
        
        public string[][] Get_Tovar_izbytok() {
            return base.Channel.Get_Tovar_izbytok();
        }
        
        public System.Threading.Tasks.Task<string[][]> Get_Tovar_izbytokAsync() {
            return base.Channel.Get_Tovar_izbytokAsync();
        }
        
        public void new_kol_after_prihod(string nazva_tovara, string TTH, string kol) {
            base.Channel.new_kol_after_prihod(nazva_tovara, TTH, kol);
        }
        
        public System.Threading.Tasks.Task new_kol_after_prihodAsync(string nazva_tovara, string TTH, string kol) {
            return base.Channel.new_kol_after_prihodAsync(nazva_tovara, TTH, kol);
        }
        
        public void new_kol_after_rashod(string nazva_tovara, string TTH, string kol) {
            base.Channel.new_kol_after_rashod(nazva_tovara, TTH, kol);
        }
        
        public System.Threading.Tasks.Task new_kol_after_rashodAsync(string nazva_tovara, string TTH, string kol) {
            return base.Channel.new_kol_after_rashodAsync(nazva_tovara, TTH, kol);
        }
        
        public string RecieveString() {
            return base.Channel.RecieveString();
        }
        
        public System.Threading.Tasks.Task<string> RecieveStringAsync() {
            return base.Channel.RecieveStringAsync();
        }
    }
}
